# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b6196724ecafe519b6b006c2ecef9eeb7a695d8b9cfe2eafe149c1651be6e3df13a5804bd00075db035dfbce53affb00bb666758d1c262e3b22e5171fc3923

test:
  secret_key_base: dd503a52a49f6e3de0e5955fc2995a5e5a2e2733264411c134cc43059e4d5604af69ee5cca602fd23f068e59aa6581dbb8945cd8714ac7db0f7fb436373b12a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
